"""Add TCPBusiness, BusinessRelation and ServiceTariff models

Revision ID: 82121fa96fc1
Revises: 59404b886985
Create Date: 2025-07-30 21:33:56.823999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82121fa96fc1'
down_revision = '59404b886985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcpbusiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False, comment='Nombre del proyecto TCP'),
    sa.Column('description', sa.Text(), nullable=False, comment='Descripción del proyecto'),
    sa.Column('main_activity', sa.String(length=255), nullable=False, comment='Actividad principal'),
    sa.Column('is_registered_in_conservation_zone', sa.Boolean(), nullable=False, comment='Registrado en las Zonas Priorizadas para la Conservación'),
    sa.Column('has_bank_account', sa.Boolean(), nullable=False, comment='Posee cuenta bancaria'),
    sa.Column('payment_method', sa.String(length=10), nullable=False, comment='Método de pago'),
    sa.Column('bank_type', sa.String(length=20), nullable=True, comment='Tipo de banco'),
    sa.Column('fiscal_bank_branch', sa.String(length=255), nullable=True, comment='Sucursal bancaria de su domicilio fiscal'),
    sa.Column('has_transportation', sa.Boolean(), nullable=False, comment='Posee un medio de transporte'),
    sa.Column('does_ecommerce', sa.Boolean(), nullable=False, comment='Realiza comercio electrónico'),
    sa.Column('location', sa.String(length=255), nullable=False, comment='Lugar donde ejerce'),
    sa.Column('residential_commercial_area', sa.Boolean(), nullable=False, comment='Área comercial en vivienda'),
    sa.Column('music_service', sa.Boolean(), nullable=False, comment='Servicio de música'),
    sa.Column('operation_hours', sa.String(length=255), nullable=False, comment='Horario de funcionamiento de la instalación'),
    sa.Column('nic', sa.String(length=50), nullable=False, comment='NIC'),
    sa.Column('business_address', sa.Text(), nullable=False, comment='Dirección del negocio'),
    sa.Column('contact_phone', sa.String(length=15), nullable=True, comment='Teléfono de contacto'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='Correo de contacto'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Fecha de creación'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('related_business_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['tcpbusiness.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_business_id'], ['tcpbusiness.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicetariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['tcpbusiness.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicetariff')
    op.drop_table('business_relation')
    op.drop_table('tcpbusiness')
    # ### end Alembic commands ###
