"""flujorad-circuito

Revision ID: 908b176497c2
Revises: 5ac41b10992d
Create Date: 2025-06-30 23:26:45.649557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '908b176497c2'
down_revision = '5ac41b10992d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuito_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'circuitos', ['circuito_id'], ['id'])

    with op.batch_alter_table('nodo_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('circuito_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('nodo_data_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'circuitos', ['circuito_id'], ['id'])
        batch_op.drop_column('general_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodo_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_data_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('nodo_data_ibfk_1'), 'general_data', ['general_data_id'], ['id'])
        batch_op.drop_column('circuito_id')

    with op.batch_alter_table('lineas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('circuito_id')

    # ### end Alembic commands ###
